services:
  - type: web
    name: flavor-server-pos
    runtime: node
    branch: feat/glass-ui
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: PUBLIC_URL
        value: https://flavor-server-0cge.onrender.com
      - key: SHOP_NAME
        value: Dinefy
